### ISSUE TITLE
Strings not being parsed from config file?

### ISSUE THREAD

**Issue by unilock** [sisby-folk/kaleido-config#2]
It seems that config class fields of type `String` aren't parsed with the rest of the config file; rather, they're always read as their default value.

To reproduce, create the following config class:

```java
public class ExampleConfig extends WrappedConfig {
    @Comment("This is an example configurable String.")
    public final String exampleString = "example_value";

    @Comment("This is an example configurable boolean.")
    public final boolean exampleBoolean = true;
}
```

With the following main class to test it:

```java
public class Main {
    public static final ExampleConfig CONFIG = ExampleConfig.createToml(Paths.get("").toAbsolutePath(), "config", "example", ExampleConfig.class)

    public static void main(String[] args) {
        System.out.println("exampleString: " + CONFIG.exampleString);
        System.out.println("exampleBoolean: " + CONFIG.exampleBoolean);
    }
}
```

When run the first time, the above code will print:

```
exampleString: example_value
exampleBoolean: true
```

Then edit the generated config file manually as such:

```toml
# This is an example configurable String.
# default: example_value
exampleString = "new_value"

# This is an example configurable boolean.
# default: true
exampleBoolean = false
```

(so, change `exampleString` to `"new_value"`, and `exampleBoolean` to `false`)

Finally, run the code again. It will print the following:

```
exampleString: example_value
exampleBoolean: false
```

`exampleString` is still read as its default value, while `exampleBoolean` is read as its updated value from the config file.

Maybe I'm doing something wrong...?
